name: fitness-rpg
title: Fitness RPG
category: Health & Fitness
description: |
  Une application de fitness gamifiée qui transforme vos entraînements en aventure RPG.
  Gagnez de l'XP, débloquez des badges et progressez dans votre aventure fitness !

developer: Your Name
website: https://github.com/yourusername/fitness-rpg
documentation: https://github.com/yourusername/fitness-rpg/blob/main/README.md

# Configuration des ports
port_map: "5000"
scheme: http

# Volumes de données
volumes:
  - container: /app/data
    host: /DATA/AppData/fitness-rpg/data
    description: "Données de l'application"
  - container: /app/logs
    host: /DATA/AppData/fitness-rpg/logs
    description: "Logs de l'application"

# Variables d'environnement
environment:
  - name: FLASK_ENV
    label: "Environment Flask"
    description: "Mode de l'application (production/development)"
    default: "production"
  - name: TZ
    label: "Timezone"
    description: "Fuseau horaire"
    default: "Europe/Paris"

# Requirements
requirements:
  - docker
  - docker-compose

# Screenshots (optionnel)
screenshots:
  - https://via.placeholder.com/800x600.png?text=Fitness+RPG+Screenshot+1
  - https://via.placeholder.com/800x600.png?text=Fitness+RPG+Screenshot+2
